#include "header.h"

void cutscene (int row,int col) {
        int y = -35;
        int direction = 1;
        initscr();
        curs_set(0);
        getmaxyx(stdscr,row,col);
        while(y + 35 < 35) {
                Boot(80);
                Wave(col,3);
                Wave(col,4);
                SeaPlant(col,row);
                mvprintw(26,119 , "     |\\     ");
                mvprintw(27,119 ,  "    |  \\     ");
                mvprintw(28,119 , "|\\ /    .\\  ");
                mvprintw(29,119 , "| |       (");
                mvprintw(30,119 , "|/ \\     /");
                mvprintw(31,119 ,    "    |  /");
                mvprintw(32,119, "     |/");
                mvprintw(y ,110,     "|        |                     |         |" );
                mvprintw(y + 1,110,  "X        X                     X         X" );
                mvprintw(y + 2,110,  "|        |                     |         |" );
                mvprintw(y + 3,110,  "X        X                     X         X" );
                mvprintw(y + 4,110,  "|        |                     |         |" );
                mvprintw(y + 5,110,  "X        X                     X         X" );
                mvprintw(y + 6,110,  "|        |                     |         |" );
                mvprintw(y + 7,110,  "X        X                     X         X" );
                mvprintw(y + 8,110,  "|        |                     |         |" );
                mvprintw(y + 9, 110, "X        X                     X         X" );
                mvprintw(y + 10,110, "|        |                     |         |" );
                mvprintw(y + 11,110, "X        X                     X         X" );
                mvprintw(y + 11,110, "|        |                     |         |" );
                mvprintw(y + 12,110, "X        X                     X         X  " );
                mvprintw(y + 13 ,110,"|        |                     |         |  " );
                mvprintw(y + 14,110, "X        ######################X##########" );
                mvprintw(y + 15 ,110,"|       #                      |       # #" );
                mvprintw(y + 16,110, "X      #                       X      # |#" );
                mvprintw(y + 17 ,110,"|     #                        |     #| |#" );
                mvprintw(y + 18 ,110,"X    #                         X    # | |#" );
                mvprintw(y + 19,110, "|   #                          |   #| | |#");
                mvprintw(y + 20,110, "X  #                           X  # | | |#");
                mvprintw(y + 21,110, "| #                            | #| | | |#");
                mvprintw(y + 22,110, "X#                             X# | | | |#");
                mvprintw(y + 23,110, "################################  | | | |#");
                mvprintw(y + 24,110, "# | | | | | | | | | | | | | | |#  | | | |#");
                mvprintw(y + 25,110, "# | | | | | | | | | | | | | | |#  | | | |# ");
                mvprintw(y + 26,110, "# | | | | | | | | | | | | | | |#  | | | |# ");
                mvprintw(y + 27,110, "# | | | | | | | | | | | | | | |#  | | | #");
                mvprintw(y + 28,110, "# | | | | | | | | | | | | | | |#  | | |# ");
                mvprintw(y + 29,110, "# | | | | | | | | | | | | | | |#  | | #");
                mvprintw(y + 30,110, "# | | | | | | | | | | | | | | |#  | |#");
                mvprintw(y + 31,110, "# | | | | | | | | | | | | | | |#  | #");
                mvprintw(y + 32,110, "# | | | | | | | | | | | | | | |#  |# ");
                mvprintw(y + 33,110, "# | | | | | | | | | | | | | | |#  #");
                mvprintw(y + 34,110, "# | | | | | | | | | | | | | | |# #");
                mvprintw(y + 35,110, "################################");
                y = y + direction;
                refresh();
                clear();
                usleep(1000*80);
        }
        while (y > -35 && y < 70 ) {
                Boot(80);
                Wave(col,3);
                Wave(col,4);
                SeaPlant(col,row);
                direction = -1;
                mvprintw(y ,110,     "|        |                     |         |" );
                mvprintw(y + 1,110,  "X        X                     X         X" );
                mvprintw(y + 2,110,  "|        |                     |         |" );
                mvprintw(y + 3,110,  "X        X                     X         X" );
                mvprintw(y + 4,110,  "|        |                     |         |" );
                mvprintw(y + 5,110,  "X        X                     X         X" );
                mvprintw(y + 6,110,  "|        |                     |         |" );
                mvprintw(y + 7,110,  "X        X                     X         X" );
                mvprintw(y + 8,110,  "|        |                     |         |" );
                mvprintw(y + 9, 110, "X        X                     X         X" );
                mvprintw(y + 10,110, "|        |                     |         |" );
                mvprintw(y + 11,110, "X        X                     X         X" );
                mvprintw(y + 11,110, "|        |                     |         |" );
                mvprintw(y + 12,110, "X        X                     X         X  " );
                mvprintw(y + 13 ,110,"|        |                     |         |  " );
                mvprintw(y + 14,110, "X        ######################X##########" );
                mvprintw(y + 15 ,110,"|       #                      |       # #" );
                mvprintw(y + 16,110, "X      #                       X      # |#" );
                mvprintw(y + 17 ,110,"|     #                        |     #| |#" );
                mvprintw(y + 18 ,110,"X    #                         X    # | |#" );
                mvprintw(y + 19,110, "|   #                          |   #| | |#");
                mvprintw(y + 20,110, "X  #                           X  # | | |#");
                mvprintw(y + 21,110, "| #                            | #| | | |#");
                mvprintw(y + 22,110, "X#                             X# | | | |#");
                mvprintw(y + 23,110, "################################  | | | |#");
                mvprintw(y + 24,110, "# | | | | | | | | | | | | | | |#  | | | |#");
                mvprintw(y + 25,110, "# | | | | | | | | | | | | | | |#  | | | |# ");
                mvprintw(y + 26,110, "# | | | |      |\\       | | | |#  | | | |# ");
                mvprintw(y + 27,110, "# | | | |     |  \\      | | | |#  | | | #");
                mvprintw(y + 28,110, "# | | | | |\\ /    x\\    | | | |#  | | |# ");
                mvprintw(y + 29,110, "# | | | | | |       (   | | | |#  | | #");
                mvprintw(y + 30,110, "# | | | | |/ \\     /    | | | |#  | |#");
                mvprintw(y + 31,110, "# | | | |     |  /      | | | |#  | #");
                mvprintw(y + 32,110, "# | | | |      |/       | | | |#  |#");
                mvprintw(y + 33,110, "# | | | | | | | | | | | | | | |#  #");
                mvprintw(y + 34,110, "# | | | | | | | | | | | | | | |# #");
                mvprintw(y + 35,110, "################################");
                y = y + direction;
                refresh();
                clear();
                usleep(1000*80);
        }
        refresh();
        usleep(1000*80);
}
